# Config File for Viper

database:
  host: postgres
  username: postgres
  password: postgres
  port: 5432
  dbname: deall_technical_test_go
  timezone: Asia/Jakarta
  enable_ssl: false
swagger_base_path: /dating-app-deall
jwt_secret: mysecret-is-kept-safely
port: 8080