name: Test and Deploy to VM
on:
  push:
    branches: [ main ]
env:
  ENV: dev
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY: ${{ secrets.SSH_KEY }}
  DIR_NAME: ${{ secrets.DEV_DIR_NAME }}
  CONTAINER_NAME: ${{ secrets.DEV_CONTAINER_NAME }}
  IMAGE_NAME: ${{ secrets.DEV_IMAGE_NAME }}
  CONTAINER_PORT: ${{ secrets.DEV_CONTAINER_PORT }}
  LOCAL_PORT: ${{ secrets.DEV_LOCAL_PORT }}
  DOCKER_NETWORK: ${{ secrets.DEV_DOCKER_NETWORK }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.x'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

  deploy:
    depends: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: |
            cd ~/${{ env.DIR_NAME }}
            echo "Pulling from main branch"
            git checkout main
            git pull
            docker compose -f docker-compose-local.yaml down
            docker compose -f docker-compose-local.yaml up -d
            echo "Deployed to VM"
            

